language: node_js
dist: trusty
sudo: required
node_js: 6

cache:
  directories:
  - node_modules

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_3fe7161daabc_key -iv $encrypted_3fe7161daabc_iv -in .env.enc -out .env -d || true'
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script:
- npm run lint
- NODE_ENV=production npm run build
env:
  global:
  - CF_APP=similarity-search-demo-james
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=jzhang300@us.ibm.com
  - CF_SPACE=dev
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: travis
    repo: jzhang300/similarity-search-nodejs
  skip_cleanup: true
notifications:
  email: false
